"""
This file is generated by salt, if you want to make any changes to it please edit
the /salt/salt_roots/base/django/superuser.py file
"""
from django.core.management.base import BaseCommand
from django.contrib.auth.models import User

class Command(BaseCommand):
    def handle(self, *args, **options):
        try:
            User.objects.get(username='admin')
        except User.DoesNotExist:
            user = User(username='admin')
            user.set_password('password')
            user.is_superuser = True
            user.is_staff = True
            user.save()